### ISSUE TITLE
Add new favicon

### ISSUE THREAD

**Issue by Steve0Greatness** [NekowebWiki/WikiGen#1]
A favicon specific to this wiki should be added at some point, so that it doesn't look like a Nekoweb tab.

**Comment by Steve0Greatness** [comment]
I'm not a great pixel artist, so getting someone who knows how to design a good favicon would be a good idea.

**Comment by SirUrchin** [comment]
Yeah, since I'm not very good in pixel art either.

**Comment by Steve0Greatness** [comment]
Alright, since I posted this in the Discord, here's an idea of what the favicon could look like:

![nekowebwikilogodemo2](https://github.com/user-attachments/assets/1ddbd6fa-be7c-492e-b6ba-86cb43c515d7)
