### ISSUE TITLE
Change out background

### ISSUE THREAD

**Issue by Steve0Greatness** [NekowebWiki/WikiGen#9]
I'm not sure if we actually can use the current background, since a GIF being uploaded to Tenor or GIPHY doesn't mean it allows for usage.

This is unless we got permission from the author.

**Comment by SirUrchin** [comment]
Yeah, I used that gif more as a dummy, since it is also kind of unsharp.

We should get a new background probably.

**Comment by Steve0Greatness** [comment]
Alright, I've added it to the to-do list.
